.aws-setup:
  before_script:
    - mkdir -p ~/.aws
    - echo "${CI_JOB_JWT_V2}" > /tmp/web_identity_token
    - echo -e "[profile oidc]\nrole_arn=${ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config

stages:
- build
- release

latex:
  stage: build
  image: registry.gitlab.com/islandoftex/images/texlive:TL2023-2024-03-10-full
  parallel:
    matrix:
    - lang: [it, en]
  script:
    - pdflatex cv-${lang}.tex
    - pdflatex cv-${lang}.tex
  after_script:
    - cat cv-${lang}.log
  artifacts:
    paths:
      - cv-${lang}.pdf

artifact-publish:
  stage: release
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  variables:
    AWS_PROFILE: oidc
  parallel:
    matrix:
    - lang: [it, en]
  before_script:
    - !reference [.aws-setup, before_script]
  script:
    - aws s3 cp cv-${lang}.pdf s3://${BUCKET_NAME}/${CI_COMMIT_REF_NAME}/${lang}.pdf
    - aws s3 cp cv-${lang}.pdf s3://${BUCKET_NAME}/${lang}.pdf
  only:
    - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
