.aws-setup:
  before_script:
    - mkdir -p ~/.aws
    - echo "${CI_JOB_JWT_V2}" > /tmp/web_identity_token
    - echo -e "[profile oidc]\nrole_arn=${ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config

stages:
- build
- release

latex:
  stage: build
  image: registry.gitlab.com/islandoftex/images/texlive:latest
  parallel:
    matrix:
    - lang: [it, en]
  script:
    - pdflatex cv-${lang}.tex
    - pdflatex cv-${lang}.tex
  after_script:
    - cat cv-${lang}.log
  artifacts:
    paths:
      - cv-${lang}.pdf

infra-preview:
  stage: build
  image: pulumi/pulumi-python
  variables:
    AWS_PROFILE: oidc
  before_script:
    - !reference [.aws-setup, before_script]
    - cd pulumi && pulumi stack select latexcv
    - python3 -m venv venv
    - venv/bin/pip install -r requirements.txt
  script:
    - pulumi preview
  only:
    - branches
    
artifact-publish:
  stage: release
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  variables:
    AWS_PROFILE: oidc
  parallel:
    matrix:
    - lang: [it, en]
  before_script:
    - !reference [.aws-setup, before_script]
  script:
    - aws s3 cp cv-${lang}.pdf s3://latexcv-artifacts/${lang}.pdf
  only:
    - main

infra-up:
  stage: release
  image: pulumi/pulumi-python
  variables:
    AWS_PROFILE: oidc
  before_script:
    - !reference [.aws-setup, before_script]
    - cd pulumi && pulumi stack select latexcv
    - python3 -m venv venv
    - venv/bin/pip install -r requirements.txt
  script:
    - pulumi up --yes
  only:
  - main