stages:
- build
# - release
# - destroy



build:
  stage: build
  image: registry.gitlab.com/islandoftex/images/texlive:latest
  parallel:
    matrix:
    - lang: [it, en]
  script:
    - pdflatex cv-${lang}.tex
  after_script:
    - cat cv-${lang}.log
  artifacts:
    paths:
      - cv-${lang}.pdf


# variables:
#   CLOUDFORMATION_STACK_NAME: latexcv-cicd-stack

# build-aws-infra:
#   stage: build
#   image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest  
#   environment:
#     name: main
#     on_stop: destroy-cf
#   script:
#     - aws cloudformation deploy --stack-name $CLOUDFORMATION_STACK_NAME --template-file iac/template.yml --capabilities CAPABILITY_NAMED_IAM
# #  only: 
# #  - main

# build:
#   stage: build
#   image: registry.gitlab.com/islandoftex/images/texlive:latest
#   script:
#     - pdflatex cv-en.tex
#     - pdflatex cv-it.tex
#     - echo PRV_JOB_ID=$CI_JOB_ID >> job-ref.env
#   after_script:
#     - cat cv-en.log
#     - cat cv-it.log
#   artifacts:
#     expire_in: 1 week
#     paths:
#       - cv-en.pdf
#       - cv-it.pdf
#     reports:
#       dotenv: job-ref.env



# release:
#   stage: release
#   image: registry.gitlab.com/gitlab-org/release-cli:latest
#   script:
#     - echo 'Generating releases..'
#   rules:
#     - if: $CI_COMMIT_TAG                 
#   release:
#     name: 'Release $CI_COMMIT_TAG'
#     description: 'Created using Gitlab-CI' 
#     tag_name: '$CI_COMMIT_TAG'                                  
#     ref: '$CI_COMMIT_TAG'
#     assets: 
#       links:
#         - name: 'cv-ita-${CI_COMMIT_TAG}'
#           url: 'https://gitlab.com/ollaww/latexcv/-/jobs/${PRV_JOB_ID}/artifacts/file/cv-it.pdf'
#         - name: 'cv-en-${CI_COMMIT_TAG}'
#           url: 'https://gitlab.com/ollaww/latexcv/-/jobs/${PRV_JOB_ID}/artifacts/file/cv-en.pdf'


# destroy-cf:
#   stage: destroy
#   environment:
#     name: main
#     action: stop
#   image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest  
#   script:
#     - aws cloudformation delete-stack --stack-name $CLOUDFORMATION_STACK_NAME
#   when: manual