stages:
- build
- release
# - destroy



latex:
  stage: build
  image: registry.gitlab.com/islandoftex/images/texlive:latest
  parallel:
    matrix:
    - lang: [it, en]
  script:
    - pdflatex cv-${lang}.tex
  after_script:
    - cat cv-${lang}.log
  artifacts:
    paths:
      - cv-${lang}.pdf

infra:
  stage: build
  image: pulumi/pulumi-python
  variables:
    PULUMI_ACCESS_TOKEN: ${PULUMI_ACCESS_TOKEN}
    CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
  before_script:
    - printenv
    - cd pulumi && pulumi stack select latexcv
    - python3 -m venv venv
    - venv/bin/pip install -r requirements.txt
  script:
    - pulumi preview

