version: 0.2

phases:
  build:
    commands:
      - pdflatex cv-en.tex
      - pdflatex cv-it.tex
    finally:
      - cat cv-en.log
      - cat cv-it.log

artifacts:
  files:
  - "*.pdf"
  - "*.log"
  secondary-artifacts:
    itacv:
      files:
        - cv-it.pdf
    encv:
      files:
        - cv-en.pdf